from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"

RAW_DIR = DATA_DIR / "raw"
RAW_ANKHANG_DIR = RAW_DIR / "ankhang"
RAW_ANKHANG_HTML_DIR = RAW_ANKHANG_DIR / "html"
RAW_CURATION_DIR = RAW_DIR / "curation"
RAW_ANKHANG_SNAPSHOTS_DIR = RAW_ANKHANG_DIR / "snapshots"

INTERIM_DIR = DATA_DIR / "interim"
PROCESSED_DIR = DATA_DIR / "processed"

TEXT_INTERIM_DIR = INTERIM_DIR / "text"
RAG_INTERIM_DIR = INTERIM_DIR / "rag"
DOCLING_INTERIM_DIR = INTERIM_DIR / "docling"
CANONICAL_INTERIM_DIR = INTERIM_DIR / "canonical"
ANKHANG_MARKDOWN_INTERIM_DIR = INTERIM_DIR / "ankhang_markdown"

RAG_FINAL_DIR = PROCESSED_DIR / "rag-final"
PROCESSED_EVALUATION_DIR = PROCESSED_DIR / "evaluation"

DATA_RUNS_DIR = DATA_DIR / "runs"
RETRIEVAL_EVAL_RUNS_DIR = DATA_RUNS_DIR / "retrieval_eval"

DATA_CACHE_DIR = DATA_DIR / "cache"
QUERY_EMBEDDING_CACHE_DIR = DATA_CACHE_DIR / "query_embeddings"
VECTOR_EMBEDDING_CACHE_DIR = DATA_CACHE_DIR / "vector_embeddings"

WORK_DIR = DATA_DIR / ".work"
RAG_FINAL_SECTIONS_PATH = RAG_FINAL_DIR / "sections.jsonl"
RAG_FINAL_CHUNKS_PATH = RAG_FINAL_DIR / "chunks.jsonl"
RAG_FINAL_MANIFEST_PATH = RAG_FINAL_DIR / "manifest.json"
RAG_FINAL_VALIDATION_PATH = RAG_FINAL_DIR / "validation_report.json"
