from __future__ import annotations

DEFAULT_EMBEDDING_MODEL = "qwen3-embedding:0.6b-fp16"
DEFAULT_RERANKER_MODEL = "qwen3-reranker:0.6b-fp16"
DEFAULT_RETRIEVER = "hybrid"
DEFAULT_CANDIDATE_K = 50
DEFAULT_RRF_K = 2
DEFAULT_TOP_K = 10
DEFAULT_REQUEST_TIMEOUT_SECONDS = 900.0
DEFAULT_BUDGET_SECONDS = 21_600
